### ISSUE TITLE
preloadBySystemJS not working as Angular 2 adapter

### ISSUE THREAD

**Issue by lmaze** [UIUXEngineering/karma-jspm#11]
If I use the Angular 2 adapter, everything works fine and my tests are getting well.

```javascript
module.exports = function(config) {
    config.set({
        basePath: '',
        frameworks: ['jspm', 'jasmine'],
        jspm: {
            stripExtension: false,
            config: "jspm.config.js",
            packages: "lib/jspm/",
            adapter: 'angular2',
            // .......................
        },
        // .........................
    })
}
```

But if I do not use the adapter and manually load the needed files with the preloadBySystemJS property, then my tests do not work.

I load the same files as those indicated here : https://github.com/UIUXEngineering/karma-jspm#preloadbysystemjs. So this is the same files loaded by the adapter.

```javascript
module.exports = function(config) {
    config.set({
        basePath: '',
        frameworks: ['jspm', 'jasmine'],
        jspm: {
            stripExtension: false,
            config: "jspm.config.js",
            packages: "lib/jspm/",
            preloadBySystemJS: [
			    'es6-shim',
                'core-js/client/shim.min.js',
                'reflect-metadata/Reflect.js',

                // Test Assistance
                'zone.js/dist/zone.js',
                'zone.js/dist/long-stack-trace-zone.js',
                'zone.js/dist/async-test.js',
                'zone.js/dist/fake-async-test.js',
                'zone.js/dist/sync-test.js',
                'zone.js/dist/proxy.js',
                'zone.js/dist/jasmine-patch.js',

                // TestBed.initTestEnvironment
                '@angular/core/testing',
                '@angular/platform-browser-dynamic/testing'
            ],
            // .......................
        },
        // .........................
    })
}
```

The error returned by Karma is as follows :

```
  Error: (SystemJS) Zone is not defined
        ReferenceError: Zone is not defined
            at Object.eval (http://localhost:9876/lib/jspm/npm/@angular/core@2.0.2/bundles/core-testing.umd.js:9:19066)
```

Is this is a bug or did I miss something?

**Comment by jerryorta-dev** [comment]
Thanks for reporting, I'll check this scenario again. 

[May be reladed to this bug](https://github.com/UIUXEngineering/angular2-jspm-typescript-seed/issues/6)

**Comment by lmaze** [comment]
Thanks ! For the related bug, i'm on Windows 10 with Chrome too.

**Comment by jerryorta-dev** [comment]
I'm seeing this issue on the Mac platform now as well. Troubleshooting.

**Comment by jerryorta-dev** [comment]
https://github.com/UIUXEngineering/karma-jspm/issues/13

**Comment by jerryorta-dev** [comment]
@lmaze, I just pushed 3.0.6 which includes a fix for this issue. I decided to allow preloadBySystemJS to ADD files to the list the 'angular2' adapter loads, thinking that in any particular use case a project may require files beyond what only angular 2 requires for testing.

**Comment by lmaze** [comment]
@jerryorta-dev I upgraded to the latest version (3.0.6) and everything seems to work. Thank you very much for the fix!
