### ISSUE TITLE
Unknown Error: "originalError"

### ISSUE THREAD

**Issue by patrickmichalina** [UIUXEngineering/karma-jspm#16]
Is there any way to debug this? I don't know what is happening here... If I remove any spec files (not loading any tests) this error goes away. If I make even the most basic .spec.ts file, this error appears.

![capture](https://cloud.githubusercontent.com/assets/6701211/19692632/43956d70-9a9e-11e6-8efd-834ccde42865.PNG)

**Comment by jerryorta-dev** [comment]
May I see your karma config and package.json jspm config? I have an idea what is going on, but don't want to make assumptions.

**Comment by patrickmichalina** [comment]
I am investigation. I think it is related to jspm.config.... I will let you know

**Comment by patrickmichalina** [comment]
OK! Think I am in business. 2 things were happening...

Need to include `'tsconfig.json` in files array and in proxies `'/tsconfig.json': '/base/tsconfig.json'`

also had an issue related to this package https://github.com/KevCJones/plugin-scss

It wasn't referencing postcss-safe-parser, so I installed that manually and it worked. 

Nice work on this project!
