### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by hoisel** [UIUXEngineering/karma-jspm#2]
START:
09 09 2016 12:33:57.206:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
09 09 2016 12:33:57.207:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
09 09 2016 12:33:57.213:INFO [launcher]: Starting browser PhantomJS
09 09 2016 12:33:57.450:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket /#AjH7GuEPIg3FGVmbAAAA with id 38504618
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  Error: (SystemJS) nstrument "jspm_packages/npm/diffie-hellman@5.0.2/lib/primes.json" for istanbul.
  	Line 2: Unexpected token :
  	Error loading http://localhost:9876/jspm_packages/npm/diffie-hellman@5.0.2/lib/primes.json!http://localhost:9876/jspm_packages/github/systemjs/plugin-json@0.1.2.js as "./lib/primes.json!systemjs-json" from http://localhost:9876/jspm_packages/npm/diffie-hellman@5.0.2/browser.js
  	Error loading http://localhost:9876/src/components/calendar/calendar.component.specs.ts

Finished in 3.937 secs / 0 secs

**Comment by jerryorta-dev** [comment]
May I see the jspm node of your package.json, as well your karma config setup?

**Comment by hoisel** [comment]
Hi @jerryorta-dev, 
Thank you for your reply. All files you need are in [this](https://github.com/prodest/es-na-palma-da-mao-mobile/tree/%40UIUXEngineering/karma-jspm) branch.

**Comment by jerryorta-dev** [comment]
Thank you for sharing the repo! I had not tested with the systemjs-json plugin, so this is a perfect environment to look into the issue. Working on it.

**Comment by jerryorta-dev** [comment]
@hoisel updgrad @uiuxengineering/karma-jspm to 2.2.20. The no longer exists in your code; the error that remains is not related to karma-jspm.

**Comment by hoisel** [comment]
Very goog, @jerryorta-dev! It worked!

**Comment by hoisel** [comment]
@jerryorta-dev, the version v.2.2.20 is running smoothly on linux and mac platforms, but crashes on windows. See the log bellow:

START:
12 09 2016 19:29:31.039:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
12 09 2016 19:29:31.055:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
12 09 2016 19:29:31.094:INFO [launcher]: Starting browser PhantomJS
12 09 2016 19:29:35.552:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket /#9AmTfhVP3g4tYME1AAAA with id 60274142
12 09 2016 19:30:35.559:WARN [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Disconnected (1 times), because no message in 60000 ms.
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  Disconnected, because no message in 60000 ms.

Finished in 1 min 0.007 secs / 0 secs

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle es-na-palma-da-mao-mobile@1.0.0-pre~pretest: es-na-palma-da-mao-mobile@1.0.0-pre
6 silly lifecycle es-na-palma-da-mao-mobile@1.0.0-pre~pretest: no script for pretest, continuing
7 info lifecycle es-na-palma-da-mao-mobile@1.0.0-pre~test: es-na-palma-da-mao-mobile@1.0.0-pre
8 verbose lifecycle es-na-palma-da-mao-mobile@1.0.0-pre~test: unsafe-perm in lifecycle true
9 verbose lifecycle es-na-palma-da-mao-mobile@1.0.0-pre~test: PATH: C:\Users\Daniel\AppData\Roaming\nvm\v4.4.5\node_modules\npm\bin\node-gyp-bin;D:\Trabalho\es-na-palma-da-mao-mobile\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\ProgramData\chocolatey\bin;C:\Users\Daniel\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Users\Daniel\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Docker Toolbox;C:\Users\Daniel\AppData\Roaming\nvm;C:\Program Files (x86)\Microsoft VS Code Insiders\bin;C:\Users\Daniel\AppData\Roaming\npm;C:\Users\Daniel\AppDa;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Docker Toolbox;%NVM_HOME%;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft VS Code Insiders\bin;C:\Users\Daniel\AppData\Roaming\npm
10 verbose lifecycle es-na-palma-da-mao-mobile@1.0.0-pre~test: CWD: D:\Trabalho\es-na-palma-da-mao-mobile
11 silly lifecycle es-na-palma-da-mao-mobile@1.0.0-pre~test: Args: [ '/d /s /c', 'karma start ./config/karma.conf.js' ]
12 silly lifecycle es-na-palma-da-mao-mobile@1.0.0-pre~test: Returned: code: 1  signal: null
13 info lifecycle es-na-palma-da-mao-mobile@1.0.0-pre~test: Failed to exec test script
14 verbose stack Error: es-na-palma-da-mao-mobile@1.0.0-pre test: `karma start ./config/karma.conf.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Daniel\AppData\Roaming\nvm\v4.4.5\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Daniel\AppData\Roaming\nvm\v4.4.5\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid es-na-palma-da-mao-mobile@1.0.0-pre
16 verbose cwd D:\Trabalho\es-na-palma-da-mao-mobile
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
19 error node v6.5.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error es-na-palma-da-mao-mobile@1.0.0-pre test: `karma start ./config/karma.conf.js`
22 error Exit status 1
23 error Failed at the es-na-palma-da-mao-mobile@1.0.0-pre test script 'karma start ./config/karma.conf.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the es-na-palma-da-mao-mobile package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     karma start ./config/karma.conf.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs es-na-palma-da-mao-mobile
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls es-na-palma-da-mao-mobile
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jerryorta-dev** [comment]
Thanks for the output, looking into this.

**Comment by jerryorta-dev** [comment]
I have pushed a fix to version 2.2.22.  
I have testing the issue on Windows 10, and seems is working.

Please note, @angular 2.0 modules are starting to be released, and I am currently working to update https://github.com/UIUXEngineering/angular2-jspm-typescript-seed to @angular2 2.0. This module may be updated to support angular 2, which may introduce breaking changes if you are working on an release candidate version.

I will work to support backward compatibility once angular 2.0 is fully released and tested with https://github.com/UIUXEngineering/angular2-jspm-typescript-seed

**Comment by hoisel** [comment]
Ok, it worked! Thanks
