### ISSUE TITLE
File not found (404) with the 0.17 beta 29 of JSPM

### ISSUE THREAD

**Issue by lmaze** [UIUXEngineering/karma-jspm#9]
Hi there !

I try to run karma-jspm with the latest 0.17 version of JSPM (0.17 beta 29) but it does not seem to work.
Everything seems to work well but Karma did not find my files. When I remove the karma-jspm plugin everything works...

I have the following error :
```
> karma start karma.conf.js

10 10 2016 17:48:36.281:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
10 10 2016 17:48:36.285:INFO [launcher]: Launching browser Chrome with unlimited concurrency
10 10 2016 17:48:36.305:INFO [launcher]: Starting browser Chrome
10 10 2016 17:48:37.289:INFO [Chrome 53.0.2785 (Windows 10 0.0.0)]: Connected on socket /#Gr7_DzNJAamu4P3jAAAA with id 88951264
Chrome 53.0.2785 (Windows 10 0.0.0) DEBUG: 'default-adapter.js running'

10 10 2016 17:48:37.589:WARN [web-server]: 404: /test/tu/specs/test.specs
Chrome 53.0.2785 (Windows 10 0.0.0) DEBUG: 'karma.loaded'
Chrome 53.0.2785 (Windows 10 0.0.0) DEBUG: 'Load prerequisite files.'
Chrome 53.0.2785 (Windows 10 0.0.0) DEBUG: 'Loading application and test files'
Chrome 53.0.2785 (Windows 10 0.0.0) DEBUG: 'KARMA ERROR ', Error{originalErr: Error{}}
Chrome 53.0.2785 (Windows 10 0.0.0) ERROR
  Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:9876/test/tu/specs/test.specs
        Error: XHR error (404 Not Found) loading http://localhost:9876/test/tu/specs/test.specs
        Error loading http://localhost:9876/test/tu/specs/test.specs
```

I have a very simple configuration just for testing.
Here is my configuration file for Karma :
```javascript
module.exports = function(config) {
  config.set({
    basePath: './',
    frameworks: ['jspm', 'jasmine'],
    jspm: {
      config: "jspm.config.js",
      browser: "jspm.browser.js",
      packages: "lib/jspm/",
      loadFiles: [
        'test/tu/specs/*.specs.js'
      ]
    },
    plugins:[
      'karma-jasmine',
      'karma-uiuxengineering-jspm',
      'karma-chrome-launcher'
    ],
    exclude: [
    ],
    preprocessors: {
    },
    reporters: ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: false,
    browsers: ['Chrome'],
    singleRun: true,
    concurrency: Infinity
  })
}
```

I have a standard JSPM configuration. The only difference is the installation directory of my packages ("lib/jspm" here). My specs files is in the "test/tu/specs" directory.

Does the plugin works well with the 0.17 version of JSPM?

**Comment by jerryorta-dev** [comment]
thanks for the input.. I'll update to jspm beta.29 to see what's up.

**Comment by jerryorta-dev** [comment]
Try adding this to your karma config outside of the jspm node:

```js
     proxies: {
      '/test/': '/base/test/'
    },
```
See [this seed example](https://github.com/UIUXEngineering/angular2-jspm-typescript-seed/blob/master/karma.conf.js#L122).  
You may have to do this for other directories.

For context, the fundamental difference with using this plugin as opposed to karma itself ( without this plugin ) is how files are loaded into the test browser and served from the file system. Karma serves from the file system, then when this plugin takes over for the tests it loads from a browser using your jspm.config.js. Karma adds the 'base' route to the served files, so the proxy is need to find the files. Hence, you may need to do this for other directories if you get more 404's.

**Comment by lmaze** [comment]
Thank you very much for your answer. In fact it works well with proxies, sorry for not having better understood how Karma worked. Your seed example is also very helpful and allowed me to set up a configuration that works.

My 404 problem seemed still combined with what looks like a bug on browserConfig property. I created another bug about it ;)
